### PR TITLE
chore: Add peerDependencies react@19

### PR DESCRIPTION
**Pull request by yanglee2421**
Add peerDependencies react@19

### CODE REVIEW

**Comment by khannedy** [comment]
+1

**Comment by vangberg** [comment]
Would it be possible to cut a new release, this is blocking upgrading to React 19?

Thank you!

**Comment by mweststrate** [comment]
0.11.0 was already published to NPM?

**Comment by vangberg** [comment]
You are right, sorry. I didn't see it under "Tags" in GitHub. Everything is fine. Thanks!

**Pull request merged**
