### PR TITLE
Support React 18

### PR DESCRIPTION
**Pull request by w3bdesign**
- Add support for React 18

### CODE REVIEW

**Comment by mweststrate** [comment]
@w3bdesign why is React 16 no longer supported? Nothing changed in the source code?

**Comment by w3bdesign** [comment]
> @w3bdesign why is React 16 no longer supported? Nothing changed in the source code?

@mweststrate 

I readded ^16.8.0 to dependencies

**Comment by bartlomiejwulff** [comment]
Please merge it 😄

**Comment by w3bdesign** [comment]
@mweststrate 

Is it possible to get this reviewed?

**Comment by mweststrate** [comment]
Sorry, thought I did so already!

**Comment by mweststrate** [comment]
Released as 0.7.0

**Pull request merged**
